// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Service = Collections['services']['schema']['_output']
export declare const services: Service[]
