//#region Import
import type { Metadata } from "next"

import Footer from "@/components/footer/footer"
import LocomotiveWrapper from "@/components/locomotive-wrapper"
import Navbar from "@/components/navbar/navbar"
import { Inter } from "next/font/google"

import "./globals.css"
//#endregion

const inter = Inter({ subsets: ["latin"] })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<LocomotiveWrapper>
				<body className={inter.className} data-scroll-container>
					<Navbar />
					<main className='relative z-0 min-h-screen min-w-[100vw]'>{children}</main>
					<Footer />
				</body>
			</LocomotiveWrapper>
		</html>
	)
}
