//#region Import
import type { Metadata } from "next"

import Footer from "@/components/footer/footer"
import LocomotiveWrapper from "@/components/locomotive-wrapper"
import Navbar from "@/components/navbar/navbar"
import { Inter } from "next/font/google"

import "./globals.css"
//#endregion

const inter = Inter({ subsets: ["latin"] })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang='en' suppressHydrationWarning>
		<LocomotiveWrapper>
			<body className={inter.className} data-scroll-container suppressHydrationWarning>
				<Navbar />
				{children}
				<Footer />
			</body>
		</LocomotiveWrapper>
	</html>
)

export default RootLayout
